; PlatformIO Project Configuration
; Targets: STM32F723E-Disco

[platformio]
default_envs = f723e_disco

[env:f723e_disco]
platform = ststm32
board = disco_f723ie
framework = stm32cube
upload_protocol = stlink
debug_tool = stlink
monitor_speed = 115200
board_build.mcu = stm32f723iek6 ; change microcontroller
board_build.f_cpu = 216000000L ; change MCU frequency

build_unflags = -Os
build_flags = 
    -O2
    -D PRINTF_FLOAT_ENABLE=1
    -D STM32F723xx
    -Wno-psabi

src_filter = +<src_cube/> -<src_arduino/>